backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: "https://getcartv10.netlify.app"
logo_url: "/images/logo.png"

locale: "en"

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - file: "src/contents/hero.json"
        label: "Hero Banner"
        name: "hero"
        fields:
          - { label: "Background Image", name: "backgroundImage", widget: "image" }
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Button Text", name: "buttonText", widget: "string" }
          - { label: "Button Link", name: "buttonLink", widget: "string" }
      - file: "src/contents/features.json"
        label: "Homepage Features"
        name: "features"
        fields:
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - { label: "Icon", name: "icon", widget: "image", required: false }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }

  - name: "blog"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/blog"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "text" }

  - name: "blog_page"
    label: "Blog Page Settings"
    files:
      - file: "src/contents/blogPage.json"
        label: "Blog Landing"
        name: "blogPage"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string", required: false }
          - { label: "Banner Image", name: "bannerImage", widget: "image", required: false }

  - name: "site_config"
    label: "Site Navigation & Footer"
    files:
      - file: "src/config.json"
        label: "Navigation & Footer"
        name: "navigation_footer"
        fields:
          - { label: "Announcement Bar", name: "announcement", widget: "string", required: false }
          - { label: "Logo Text", name: "logoText", widget: "string", required: false }
          - { label: "Logo Image", name: "logoImage", widget: "image", required: false }
          - label: "Header Links"
            name: "headerLinks"
            widget: "list"
            fields:
              - { label: "Label", name: "menuLabel", widget: "string" }
              - { label: "URL", name: "menuLink", widget: "string" }
          - label: "Footer Links"
            name: "footerLinks"
            widget: "list"
            fields:
              - { label: "Column Label", name: "subTitle", widget: "string" }
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "URL", name: "link", widget: "string" }

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/pages"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "components"
    label: "Components"
    label_singular: "Component"
    folder: "src/components"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Component Name", name: "name", widget: "string" }
      - { label: "Code", name: "body", widget: "text" }

  - name: "helpers"
    label: "Helpers"
    label_singular: "Helper"
    folder: "src/helpers"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Helper Name", name: "name", widget: "string" }
      - { label: "Code", name: "body", widget: "text" }
